# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Date-Biorhythm
version:      1.2
version_from: lib/Date/Biorhythm.pm
installdirs:  site
requires:
    Class::Data::Inheritable:      0
    Date::Business:                1.2
    Date::Calc:                    0
    Moose:                         0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
